language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
<<<<<<< HEAD
  - provider: releases
    api_key:
      secure: ekGNVJaYP3u6Rf885V95YNuKMIW0X0jWanqfynwOz8UOcjOhi1VF/pUti6ErFb51Z59s1HH14RnHEh4/7iw1+4MTsiu7emTIDhFlsyq9CpDBWynk8RcKxgG81KBSXn1y2XKV1wBw5MozZg7shgiMh12AJC8Y1XcR9pk2kgc+Vqe/5WMk5Bou5wwB2PuntqW3uv66OLLSyQin5joHhTZWwtmRdNmjoC4JrRqNfvP1yw1ZcJ6E9QzljaUpXktpjBecx86i1p4qu5Jw0BymlasZD5YZGhpA06eyMG2iTALX4S+APvU6QvGdG/4r+gd9QwrpaAVyjRvdeeDoRRMmTg9Qjk60aNx8CSGmd+vBXV6JIa7tLY/mRFSJ9g2ifPzLjjKUfQoE8UX+55jZGPhob5yRuuuUTMOHf+ykPbJJmNkBN4QcGpStdV8D6bljP/JHlJVzD/gjYHQ/aNYMbeoPeeW2xhmf+TH43Kb59MgyMzXbRpkMjlUQN0Pau8T+UYSRuIrgfnxyO2fmcqEhMR9kJ7HbNXlC9mW+omqbzKz27OcMdto2UsPwZqxiE6BLc/Ru+KUr2RQB2RginfSbQklvE4aSsTEIpxrgaRkzJoiUn8etqr1VjKOKnGdaXJ5vTGk0i9p3dAq6bUv57kEy1MYsuG02jyvqKtM4mFkyr9/JU6wF2z8=
    file: dist.zip
    on:
      tags: true
      repo: hms-dbmi/higlass-multivec
      branch: master
  - provider: npm
    email: pkerpedjiev@gmail.com
    api_key:
      secure: HTt6jfQDv2jJXTEx46gPGgbObgcenljrfb1KZ9sZNaXK1IoDL9yBvXudP1nT082j0FXTaH3WPNeyzJsHegrFYNFiOmxmdMuvGnLvGVvWpvGvePgso2T1pZb92GuVJ0zD+rQD4r2FgbR2mIH6z7iUxMVsJm0gi3F9TH/fGcTZ/OFoKfqGosMkeFA32f5WYm0Q02K8ZD1JjRa9VOYNzrAWNsz7J4VMuXirblkmbKz7c0sTeGGDf3emo3TzYbliUKbVtetS0h1wGXTohc26nJM9i5Bfg5t3V+6AA7j4sRMdx35sMK3CjQ2hz1Qmtqb1xHNZxNQhfBS94+BYB6XdweXXB/NueuNAwl62JQ7W2Qqa5VAfl/IuXkDojz6/k3XTwy9VYakN+hGmkAXZ5hBZ1y7/sB3AczBjndWEVpahTA+3ytLRHS/EwN0tIgWtsfjMPhhXkdwWQxQvDMp2RNBLZf1cmAzAvj1zSB5kYQWisC5pfUaZtnYlYj+txL6B2nUQUfmPqevAuLUfBRSJV1MBwco1UXNHEQvHgHA5FiQahygp6CC9wFe2SrgDhm6KlBeJzTPhme8VHfk3/ttKcBEyGSac3/zeliXi/NB7AA6phHRXPu5Z9NaiZctIPOEh9qhPXqSlqjDGoY4Yc78Lm+l3NvK5PvMKvPjI2hqwqayjC9nYyo4=
    on:
      tags: true
      branch: master
      repo: hms-dbmi/higlass-multivec
=======
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FWiFJvViaWIZkqYAfQjGNE4nh3DmTpz9snxzYAqit/p1RsgTP0qebuBo1VKpE/6DB59SRAbeLb2YYxWZS1xytx9Ccz5DjrbVwF1cMpdc2PlILVauOwVo1Cq9HEE8Qhp8Xfp3n9nlWNPVpXAbG7gMWORVhxgq9OE7mh+pW3We/p9b4ENBWIw+pSi2sH4f++FP4LyOFksYiHR4z0e5p8uMGY/KiJMdifZ9UVdJSh6PVjQTHLxBZTCqg3PRq8NeuUKQhDgnaS8s8t+sxCsSZI3UEJnQleBoHmS8/pQmERlIbGcd2YB+OrGXM3wURrXkJpT2N0mT/L8kMwy+rQXpohom+deAl/hJsq5VDRcbantNVrIw8JqKs1ghfDBQnPobcLXLvPRibaAKKpqtOiia9hK7FgmYXUDvUapbJRB+3fJhaMAyg0l97xlbe+TPwJ3bL1gbjVB90lbLTZpCdfKEf4zH2rz8agbzNmvCGuVr/DgiprkSeEDbLEt/HURwZ2P+yVnPk4zw9hKQ7Uu9YSKyXgUkBWBzw+tPjmsuqJlFsKqOsYFVx9qALOkSMJdPyW++L+b3U9Y4uhNHJfXQ1Hgn3GoaXDLErt+ik41+m8ajjpNWrST0EiNRPGSjMny8juCCIm83uMIO3PVM8O+RhPR0KpDdbfB5xU2lmWpD7fL7BjJ488Q=
  file: dist.zip
  on:
    tags: true
    branch: master
    repo: daniellenguyen/higlass-multivec
  provider: npm
  email: daniellenguyen77@gmail.com
  api_key:
    secure: VpnlHM/SQMjp3SiaYREeqFtmygUxeKt20Bh0MGKdBUFTlLdBNX+6YW3Q2ucgKnTFmdQMkWkzMdSA2Ly3Z7+pqPQYQeCiPXlNZfdQWtwp4IbR6XWYUt+049Lx/tLsWhrDNhNw8oRbt5VWQHm/Km8dswCb19fgO8xTFEUphjl+l45NIDWm/Ui1DE8c5TRvg9kG4+sjD71DN959k0zBgzVM/Y//Rlu+jBwIIIa76oMszxdDsauy8ti8X3Hm2jbImzZ00v55iEMsVGoTa6nZ3/C61ghCAV7IEA1B5r1BtQE7D0rjRIlbn+MhId2rrjYg60wfZ77StB2vE/JAJa9zd56/bO/un787mbVWRTV0YjzLoal0kwG6GK5cO5PdvmarTM2ZBTtJ1y+TlUedB+2mN2nnE0aAYPMAGRUPbwCBv8aXCM38RZnHNOvH4abjQXDercRQtT7R8Bs6kzbrxBKaOt0oZFZhAU+4erZn1H58d6XscEbv/OF6mwfxx6sufLcxsh4a8EkFOlel7J/heNsg+SAhcc4B5SATaBvkWJbNDuuayw62VZLtkkCarhyk7+ouCHtOBdFWBhtEapt7gsN1T7t1zP5LtdI6nrJQwgBQlNZMKZFj/TfEMueDHacHzeqZJ6cse4/XQUPT4WhCeE9GggvMlEkgbWd3MPI+MyM8toxoW88=
  on:
    tags: true
    repo: daniellenguyen/higlass-multivec
>>>>>>> 1c5f671d6fcc0ced8058529a80c69f6b1df311b3
