language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
addons:
  apt:
    packages:
      - xvfb
install:
    - npm install -g xvfb-maybe
before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install --quiet -g gulp
    - npm install
script:
    - npm run build
    - xvfb-maybe ./node_modules/karma/bin/karma start karma.conf.js --single-run
before_deploy:
    - npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: qVTt8MMZAOtabn3nQJak/biBdtqjdE8VnCrh9qrTIZRbDWUncLMLP0gVuWoTEo6YBsA9joVTvd+qb0RjOA0SSwKDgcAO3aTLFjfmUUqtY7PtyQ/LvyYGDbcbneN2hEFFumaTbrCyue4R1XUQsK+U8/GJ1RUGI9AQpio6vWcy/g+Dvy8luFvbR2cJtMj+2Jt4fEdx/a4tVO66Tz5uhtAB+P8UJOhGN8+NRqnQ+IJRhudOzJi/nXnTvLjt+CwozJIM8ARQjEtf+RwEY+VD82Uz38J++PkHzfSwlJ9ZOYNGpj6y0bAo4FEdsjSDH0VCrOwgY+VBtyDocGnDgCyXrQV1qS8rdX5qiiuhKnchOODCd3HDE+2NUpCNreV0fMoZ7cfRAUIoTv2KnCijg0u1PPpMxGYmtrvRN17XfOjM0BV8kvybeBsWr1LprRNUEN29sYsHieWudo6F3K5xuT2q8ewdDtcWNgRfq1qUweHDZEwD3cXYWjUoS5sxOOfhfrJ/HDmj19ss4olxMODG5vdY5meId9IoszLsrtbRbTcLSgU9gz7tbaHKjpQwqlwb4YxOjapNctefgG5kyeMSwcdMRK6Jh5kZip5+drsT4+OFx6Z28RJ9B73bGqnRvrLqoa933Lcj65bMjXLx/mAx6G+6yV5ipKPP0awhMUIiTCLzB/RXkk8=
    file: dist.zip
    on:
      tags: true
      branch: master
      repo: hms-dbmi/higlass-multivec
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
        secure: f5cmo68Zxb4lWiSnPkLLTCdZR30LPnnPmJEUh+BhZy5jhyoelKg1MQBR1UUw1HjNptMDtW3s3aodxloFSsRlQu5QvHTlyyMuCm83xSP1NCEw1WdY/TiCjRty3xNUs20AKxn8feFfvNwIP0WyBR7d36LB75JOS9Dp+Vn5ilmGD2kM6urjq0dQZdvcoNN2dzWPgTW76UMyunQjPVBS2JV3yL4zOQwh1N0gmGrdr/xjj0BYJK84vGDRaD/87n9PGPovNq8N+8enexiCKC6DL83Wc60PKYvAE5uvzcsgXwA8vhDlbMRnAWRg1pS3UdfsEQ1BjHyFODxzxqaT1mS9KtAYyltexbQ+ymYIhSvpnS6BOALl+clEVIC4VRBNMpEanYlR6wq/iRqhIQKMAVOW6PD7C1OHtPtFkB+165gb1m2GYOXP7MpiuES8sSTyj6gxN4rDupVAVWYMRJg+70p73/4n7aXBl+5qIjQiNSzFMtgoz7+B/VPr4JrMbp7aqZmjykOXT7YWtxXa3ALaXUMz8RjpKRFZILdoeUTuhHUpQ34yybhSekBa4TB+Vly0tOTMEirXT/a6bZFZZtzGw0js0ktc29ArEsVLx0Arskr3VqET1w5lQwW3bNLHwtlSpumDcnI7MT4eS5Yq22cqNRb2PRUYIJStRFxwpbF+VZ5ZSJ+T2/M=
    on:
      tags: true
      branch: master
      repo: hms-dbmi/higlass-multivec