language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: qVTt8MMZAOtabn3nQJak/biBdtqjdE8VnCrh9qrTIZRbDWUncLMLP0gVuWoTEo6YBsA9joVTvd+qb0RjOA0SSwKDgcAO3aTLFjfmUUqtY7PtyQ/LvyYGDbcbneN2hEFFumaTbrCyue4R1XUQsK+U8/GJ1RUGI9AQpio6vWcy/g+Dvy8luFvbR2cJtMj+2Jt4fEdx/a4tVO66Tz5uhtAB+P8UJOhGN8+NRqnQ+IJRhudOzJi/nXnTvLjt+CwozJIM8ARQjEtf+RwEY+VD82Uz38J++PkHzfSwlJ9ZOYNGpj6y0bAo4FEdsjSDH0VCrOwgY+VBtyDocGnDgCyXrQV1qS8rdX5qiiuhKnchOODCd3HDE+2NUpCNreV0fMoZ7cfRAUIoTv2KnCijg0u1PPpMxGYmtrvRN17XfOjM0BV8kvybeBsWr1LprRNUEN29sYsHieWudo6F3K5xuT2q8ewdDtcWNgRfq1qUweHDZEwD3cXYWjUoS5sxOOfhfrJ/HDmj19ss4olxMODG5vdY5meId9IoszLsrtbRbTcLSgU9gz7tbaHKjpQwqlwb4YxOjapNctefgG5kyeMSwcdMRK6Jh5kZip5+drsT4+OFx6Z28RJ9B73bGqnRvrLqoa933Lcj65bMjXLx/mAx6G+6yV5ipKPP0awhMUIiTCLzB/RXkk8=
    file: dist.zip
    on:
      tags: true
      branch: master
      repo: hms-dbmi/higlass-multivec
  - provider: npm
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: HTt6jfQDv2jJXTEx46gPGgbObgcenljrfb1KZ9sZNaXK1IoDL9yBvXudP1nT082j0FXTaH3WPNeyzJsHegrFYNFiOmxmdMuvGnLvGVvWpvGvePgso2T1pZb92GuVJ0zD+rQD4r2FgbR2mIH6z7iUxMVsJm0gi3F9TH/fGcTZ/OFoKfqGosMkeFA32f5WYm0Q02K8ZD1JjRa9VOYNzrAWNsz7J4VMuXirblkmbKz7c0sTeGGDf3emo3TzYbliUKbVtetS0h1wGXTohc26nJM9i5Bfg5t3V+6AA7j4sRMdx35sMK3CjQ2hz1Qmtqb1xHNZxNQhfBS94+BYB6XdweXXB/NueuNAwl62JQ7W2Qqa5VAfl/IuXkDojz6/k3XTwy9VYakN+hGmkAXZ5hBZ1y7/sB3AczBjndWEVpahTA+3ytLRHS/EwN0tIgWtsfjMPhhXkdwWQxQvDMp2RNBLZf1cmAzAvj1zSB5kYQWisC5pfUaZtnYlYj+txL6B2nUQUfmPqevAuLUfBRSJV1MBwco1UXNHEQvHgHA5FiQahygp6CC9wFe2SrgDhm6KlBeJzTPhme8VHfk3/ttKcBEyGSac3/zeliXi/NB7AA6phHRXPu5Z9NaiZctIPOEh9qhPXqSlqjDGoY4Yc78Lm+l3NvK5PvMKvPjI2hqwqayjC9nYyo4=
    on:
      tags: true
      branch: master
      repo: hms-dbmi/higlass-multivec
